import './sass/main.scss';
import './js/main-page-rendering';
import './js/header';
import './js/modal';
import './js/pagination';
import './js/modal-team';
import './js/theme-switch';
import './js/events';
import './js/button-up';